# Generated by Django 5.0 on 2023-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
