# Generated by Django 5.0 on 2023-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewTitle',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
